// src/models/sequelize/cv/Lead.js
export default (sequelize, DataTypes) => {
    const Lead = sequelize.define('Lead', {
        idlead: { type: DataTypes.INTEGER, primaryKey: true },
        gestor: { type: DataTypes.JSONB },
        imobiliaria: { type: DataTypes.JSONB },
        corretor: { type: DataTypes.JSONB },
        situacao_id: { type: DataTypes.INTEGER },
        situacao_nome: { type: DataTypes.STRING(100) },
        nome: { type: DataTypes.STRING(255) },
        email: { type: DataTypes.STRING(255) },
        telefone: { type: DataTypes.STRING(50) },
        score: { type: DataTypes.INTEGER },
        data_cad: { type: DataTypes.DATE },
        midia_principal: { type: DataTypes.STRING(100) },
        documento_tipo: { type: DataTypes.STRING(50) },
        documento: { type: DataTypes.STRING(100) },
        sexo: { type: DataTypes.STRING(10) },
        renda_familiar: { type: DataTypes.STRING(50) },
        valor_negocio: { type: DataTypes.STRING(50) },
        cep: { type: DataTypes.STRING(20) },
        endereco: { type: DataTypes.STRING(255) },
        numero: { type: DataTypes.STRING(20) },
        bairro: { type: DataTypes.STRING(100) },
        complemento: { type: DataTypes.STRING(100) },
        estado: { type: DataTypes.STRING(50) },
        cidade: { type: DataTypes.STRING(100) },
        profissao: { type: DataTypes.STRING(100) },
        origem: { type: DataTypes.STRING(100) },
        data_reativacao: { type: DataTypes.DATE },
        data_vencimento: { type: DataTypes.DATE },
        ultima_data_conversao: { type: DataTypes.DATE },
        codigointerno: { type: DataTypes.INTEGER },
        valor_venda: { type: DataTypes.DECIMAL(14, 2) },
        tags: { type: DataTypes.JSONB },
        empreendimento: { type: DataTypes.JSONB },
        interacao: { type: DataTypes.JSONB },
        autor_ultima_alteracao: { type: DataTypes.STRING(255) },
        qtde_simulacoes_associadas: { type: DataTypes.INTEGER },
        qtde_reservas_associadas: { type: DataTypes.INTEGER },
        link_interacoes: { type: DataTypes.STRING(500) },
        link_simulacoes: { type: DataTypes.STRING(500) },
        link_reservas: { type: DataTypes.STRING(500) },
        link_interesses: { type: DataTypes.STRING(500) },
        idrd_station: { type: DataTypes.STRING(100) },
        link_rdstation: { type: DataTypes.STRING(500) },
    }, {
        tableName: 'leads',
        underscored: true,
        timestamps: true,   // created_at, updated_at
    });

    return Lead;
};
